### ISSUE TITLE
Contributing guideline

### ISSUE THREAD

**Issue by TimPietrusky** [freegyes/MakingItRealm#28]
Instead of having the [contribution guideline in Facebook](https://www.facebook.com/groups/mircreators/permalink/957573134994403/), it would be nice to have a this in `.github/CONTRIBUTING.md`, like https://github.com/NERDDISCO/luminave/blob/master/.github/CONTRIBUTING.md.

**Comment by freegyes** [comment]
Thanks for the idea and the example!

I've created the first draft: https://github.com/freegyes/MakingItRealm/blob/main/CONTRIBUTING.md and linked it to the README.md.

**Comment by TimPietrusky** [comment]
Thank you @freegyes <3
